apiVersion: v1
kind: Service
metadata:
  name: oj-backend
spec:
  type: LoadBalancer
  selector:
    app: oj-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000  # 컨테이너의 포트 번호
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: oj-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: oj-backend
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 55
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: oj-judge
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: oj-judge
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: oj-redis
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: oj-redis
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: oj-postgres
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: oj-postgres
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

